version: '3.8'

services:

  mongo:
    container_name: mongo
    image: mongo:6.0.5
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: docker/php
    ports:
      - '9000:9000'
    volumes:
      - ../../backend/api:/var/www/symfony_docker
    networks:
      - app-network

  nginx_api:
    container_name: nginx_api
    image: nginx:stable-alpine
    ports:
      - '8082:80'
    volumes:
      - ../../backend/api:/var/www/symfony_docker
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - app-network

  vue:
    container_name: vue
    build:
      context: docker/vue
    ports:
      - '8080:8080'
    volumes:
      - ../../frontend/api:/app
    networks:
      - app-network

volumes:
  mongodb_data_container:

#Docker Networks
networks:
  app-network:
    driver: bridge